// GENERATED by scripts/generate-incident-index.ts — do not edit by hand.
// One static import per vendored bundle so esbuild inlines them all.
import b_axios_mar26 from './axios-mar26.json' with { type: 'json' };
import b_node_ipc_may26 from './node-ipc-may26.json' with { type: 'json' };
import b_shai_hulud_jun26 from './shai-hulud-jun26.json' with { type: 'json' };

export const VENDORED_INCIDENTS = [b_axios_mar26, b_node_ipc_may26, b_shai_hulud_jun26];
