/**
 * Regenerates packages/cli/src/data/incidents/index.ts from the *.json bundles
 * in that directory. Static imports keep esbuild inlining the data into the
 * single-file build (vendored advisories ship inside the npm artifact).
 * Run after adding a bundle: node --experimental-strip-types scripts/generate-incident-index.ts
 * (incident-bundle.yml runs it automatically).
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dir = resolve(import.meta.dirname, '..', 'packages', 'cli', 'src', 'data', 'incidents');
const bundles = readdirSync(dir)
  .filter((f) => f.endsWith('.json') && !f.startsWith('_'))
  .sort();

const ident = (file: string): string =>
  `b_${file.replace(/\.json$/, '').replace(/[^a-zA-Z0-9]/g, '_')}`;

const lines = [
  '// GENERATED by scripts/generate-incident-index.ts — do not edit by hand.',
  '// One static import per vendored bundle so esbuild inlines them all.',
  ...bundles.map((f) => `import ${ident(f)} from './${f}' with { type: 'json' };`),
  '',
  `export const VENDORED_INCIDENTS = [${bundles.map(ident).join(', ')}];`,
  '',
];

writeFileSync(join(dir, 'index.ts'), lines.join('\n'));
console.log(`✓ generated incidents/index.ts with ${bundles.length} bundles`);
